name: dart_language_server
version: 0.1.16
description: >-
  A wrapper around the Dart analysis server with the --lsp flag.
homepage: https://github.com/natebosch/dart_language_server

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  path: ^1.4.1

executables:
  dart_language_server: dart_language_server
