name: dart_language_server
version: 0.2.0-dev
description: Tools for writing an LSP server
homepage: https://github.com/natebosch/dart_language_server

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  async: ^2.0.0
  json_rpc_2: ^2.0.3
  stream_channel: ^2.0.0

dev_dependencies:
  build_runner: ^1.0.0
  message_builder: ^0.1.6
  pedantic: ^1.9.0
  test: ^1.0.0
